name: order-management

services:

  order-management:
    build: .
    ports:
      - "8080:8080"
    environment:
      - INVENTORY_HOST=localhost
      - INVENTORY_PORT=8080
      - MACHINE_HOST=localhost
      - MACHINE_PORT=8080
      - KAFKA_BROKER_HOST=kafka
      - KAFKA_BROKER_PORT=29092